#!/bin/bash
# Author: Sarah Barron
# Module: Computer Systems and Networks
# Assignment-1: Linux Shell Scripting 

# Description: AddBizz
# A script which updates the address book file with details of a 
# new business. The script takes 5 command line arguments. 
# The company Name, contact name and Email address are required the rest of the arguments can be null.

# Check for a duplicate before adding a new contact
./FindBiz dupl "$5" 

# if the check for a duplicate returns true exit back to the main menu without saving the contact
if [ $? -eq 0 ]
then
	exit 1

# Otherwise append the 5 arguments seperated by a | dilimiter to the BusinessDetails.txt file
else
	echo $1'|'$2'|'$3'|'$4'|'$5 >> BusinessDetails.txt
	echo "-----------------------------------------------------------------------------------------------------------"
	echo
	echo "Company Details Added: "
	echo "$1, $2, $3, $4, $5"
	exit 0
fi
